"""empty message

Revision ID: 0a22041ea1a4
Revises: None
Create Date: 2016-02-18 11:13:37.728060

"""

# revision identifiers, used by Alembic.
revision = '0a22041ea1a4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('user', sa.String(length=10), nullable=False),
    sa.Column('pwd', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('hakbun', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    ### end Alembic commands ###
