"""empty message

Revision ID: 29646a8b3f73
Revises: 0a22041ea1a4
Create Date: 2016-02-18 11:16:37.885856

"""

# revision identifiers, used by Alembic.
revision = '29646a8b3f73'
down_revision = '0a22041ea1a4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('person', 'user',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person', 'user',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               nullable=False)
    op.drop_column('person', 'id')
    ### end Alembic commands ###
