"""URL을 위한 DB를 만들었습니다 - jmg.

Revision ID: 4d05aeb1e963
Revises: None
Create Date: 2016-02-19 12:49:07.191313

"""

# revision identifiers, used by Alembic.
revision = '4d05aeb1e963'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('URL',
    sa.Column('link', sa.String(length=50), nullable=False),
    sa.Column('ID', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('link')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('URL')
    ### end Alembic commands ###
