"""URL db의 변수명을 수정했습니다. ID -> username -jmg7173

Revision ID: 74150ce036d9
Revises: fec9ce1da9ff
Create Date: 2016-02-23 16:52:35.233963

"""

# revision identifiers, used by Alembic.
revision = '74150ce036d9'
down_revision = 'fec9ce1da9ff'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('URL', sa.Column('username', sa.String(length=50), nullable=True))
    op.drop_column('URL', 'ID')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('URL', sa.Column('ID', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('URL', 'username')
    ### end Alembic commands ###
