"""외부아이디를 추가할 수 있는 DB를 추가했습니다! -jmg7173

Revision ID: 8d2145e0ef0a
Revises: 8fdb95a77994
Create Date: 2016-03-06 21:19:42.388842

"""

# revision identifiers, used by Alembic.
revision = '8d2145e0ef0a'
down_revision = '8fdb95a77994'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('externalaccount',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('sitename', sa.String(length=50), nullable=False),
    sa.Column('site_username', sa.String(length=50), nullable=False),
    sa.Column('registered_time', sa.DateTime(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('idx')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('externalaccount')
    ### end Alembic commands ###
