"""Real Name을 위한 초석입니다! 단계 3. 나머지 Column들을 삭제합니다.

Revision ID: 8fdb95a77994
Revises: 57a8604ea770
Create Date: 2016-03-02 13:41:20.351077

"""

# revision identifiers, used by Alembic.
revision = '8fdb95a77994'
down_revision = '57a8604ea770'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name_en')
    op.drop_column('user', 'middle_name_en')
    op.drop_column('user', 'first_name_kr')
    op.drop_column('user', 'first_name_en')
    op.drop_column('user', 'last_name_kr')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name_kr', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False))
    op.add_column('user', sa.Column('first_name_en', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False))
    op.add_column('user', sa.Column('first_name_kr', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False))
    op.add_column('user', sa.Column('middle_name_en', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
    op.add_column('user', sa.Column('last_name_en', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False))
    ### end Alembic commands ###
