"""empty message

Revision ID: 9a194199d017
Revises: 29646a8b3f73
Create Date: 2016-02-18 11:59:09.145181

"""

# revision identifiers, used by Alembic.
revision = '9a194199d017'
down_revision = '29646a8b3f73'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('user', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), server_default=sa.text("''"), nullable=False),
    sa.Column('pwd', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('hakbun', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###
