"""업적/업적카테고리/업적기록(달성+대기)를 위한 DB를 설계했어요. -minhoryang

Revision ID: ac6b0bec503a
Revises: 8fdb95a77994
Create Date: 2016-04-01 19:14:33.447504

"""

# revision identifiers, used by Alembic.
revision = 'ac6b0bec503a'
down_revision = '8fdb95a77994'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('_categories', sa.String(length=50), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('creators_issue_idx', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('name')
    )
    op.create_table('achievementcategory',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('name')
    )
    op.create_table('achievementstatusforautomaticapproval',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('achievement_idx', sa.Integer(), nullable=False),
    sa.Column('target_username', sa.String(length=50), nullable=False),
    sa.Column('target_progress_percent', sa.Integer(), nullable=True),
    sa.Column('target_status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('achievementstatusformanualapproval',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('achievement_idx', sa.Integer(), nullable=False),
    sa.Column('waiting_username', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('acquiredachievement',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('achievement_idx', sa.Integer(), nullable=True),
    sa.Column('when', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('idx')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acquiredachievement')
    op.drop_table('achievementstatusformanualapproval')
    op.drop_table('achievementstatusforautomaticapproval')
    op.drop_table('achievementcategory')
    op.drop_table('achievement')
    ### end Alembic commands ###
