"""Photo db를 추가했습니다 -jmg7173

Revision ID: dbdb246795ee
Revises: 74150ce036d9
Create Date: 2016-02-23 18:47:43.269038

"""

# revision identifiers, used by Alembic.
revision = 'dbdb246795ee'
down_revision = '74150ce036d9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('photo', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    ### end Alembic commands ###
