"""empty message

Revision ID: f86b05f1b379
Revises: 9a194199d017
Create Date: 2016-02-18 12:21:15.012020

"""

# revision identifiers, used by Alembic.
revision = 'f86b05f1b379'
down_revision = '9a194199d017'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('usr', sa.String(length=20), nullable=True),
    sa.Column('pwd', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('hakbun', sa.Integer(), nullable=True),
    sa.Column('last_login', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('usr')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
